/* empty css                      */import{a as g,S as h,i as a}from"./assets/vendor-DQvd0HNi.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&n(s)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();const b="https://pixabay.com/api/",L="55083969-985dcd53ed8fb60fc84f8ef8d";async function q(o,t=1){return(await g.get(b,{params:{key:L,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t}})).data}const u=document.querySelector(".gallery"),d=document.querySelector(".loader"),p=document.querySelector(".load-more"),v=new h(".gallery a",{captionsData:"alt",captionDelay:250});function w(){u.innerHTML=""}function M(o){return o.map(({webformatURL:t,largeImageURL:i,tags:n,likes:e,views:r,comments:s,downloads:m})=>`
      <li class="gallery-item">
        <a href="${i}">
          <img src="${t}" alt="${n}" />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${e}</p>
          <p><b>Views:</b> ${r}</p>
          <p><b>Comments:</b> ${s}</p>
          <p><b>Downloads:</b> ${m}</p>
        </div>
      </li>
    `).join("")}function P(o){const t=M(o);u.insertAdjacentHTML("beforeend",t),v.refresh()}function S(){d.style.display="block"}function B(){d.style.display="none"}function $(){p.style.display="block"}function f(){p.style.display="none"}const E=document.querySelector(".form"),R=document.querySelector(".load-more");let l="",c=1;const O=15;f();async function y(o=!1){o&&(w(),c=1),f(),S();try{const t=await q(l,c);if(t.hits.length===0&&o){a.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}P(t.hits);const i=Math.ceil(t.totalHits/O);if(c<i?$():a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),!o){const n=document.querySelector(".gallery li");if(n){const{height:e}=n.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}}}catch(t){console.error(t),a.error({message:"Сталася помилка при запиті!",position:"topRight"})}finally{B()}}E.addEventListener("submit",o=>{if(o.preventDefault(),l=o.currentTarget.elements["search-text"].value.trim(),!l){a.warning({message:"Введіть текст для пошуку!",position:"topRight"});return}y(!0)});R.addEventListener("click",()=>{c+=1,y()});
//# sourceMappingURL=index.js.map
