/* empty css                      */import{a as g,S as h,i as c}from"./assets/vendor-DQvd0HNi.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const b="https://pixabay.com/api/",L="55083969-985dcd53ed8fb60fc84f8ef8d";async function q(o,t=1){return(await g.get(b,{params:{key:L,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t}})).data}const u=document.querySelector(".gallery"),d=document.querySelector(".loader"),f=document.querySelector(".load-more"),v=new h(".gallery a",{captionsData:"alt",captionDelay:250});function M(){u.innerHTML=""}function P(o){return o.map(({webformatURL:t,largeImageURL:n,tags:i,likes:e,views:r,comments:s,downloads:m})=>`
      <li class="gallery-item">
        <a href="${n}">
          <img src="${t}" alt="${i}" />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${e}</p>
          <p><b>Views:</b> ${r}</p>
          <p><b>Comments:</b> ${s}</p>
          <p><b>Downloads:</b> ${m}</p>
        </div>
      </li>
    `).join("")}function w(o){const t=P(o);u.insertAdjacentHTML("beforeend",t),v.refresh()}function B(){d.style.display="block"}function S(){d.style.display="none"}function $(){f.style.display="block"}function p(){f.style.display="none"}const E=document.querySelector(".form"),R=document.querySelector(".load-more");let l="",a=1;const O=15;p();async function y(o=!1){B(),p();try{const t=await q(l,a);if(o&&M(),t.hits.length===0&&o){c.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}w(t.hits);const n=Math.ceil(t.totalHits/O);if(a<n?$():a>=n&&!o&&c.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),!o){const i=document.querySelector(".gallery li");if(i){const{height:e}=i.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}}}catch(t){console.error(t),c.error({message:"Сталася помилка при запиті!",position:"topRight"})}finally{S()}}E.addEventListener("submit",o=>{if(o.preventDefault(),l=o.currentTarget.elements["search-text"].value.trim(),!l){c.warning({message:"Введіть текст для пошуку!",position:"topRight"});return}a=1,y(!0)});R.addEventListener("click",()=>{a+=1,y()});
//# sourceMappingURL=index.js.map
